<script src="{{asset('/lib/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('/lib/jquery-ui/ui/widgets/datepicker.js')}}"></script>
    <script src="{{asset('/lib/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('/lib/perfect-scrollbar/perfect-scrollbar.min.js')}}"></script>
    <script src="{{asset('/lib/moment/min/moment.min.js')}}"></script>
    <script src="{{asset('/lib/peity/jquery.peity.min.js')}}"></script>
    <script src="{{asset('/lib/rickshaw/vendor/d3.min.js')}}"></script>
    <script src="{{asset('/lib/rickshaw/vendor/d3.layout.min.js')}}"></script>
    <script src="{{asset('/lib/rickshaw/rickshaw.min.js')}}"></script>
    <script src="{{asset('/lib/jquery.flot/jquery.flot.js')}}"></script>
    <script src="{{asset('/lib/jquery.flot/jquery.flot.resize.js')}}"></script>
    <script src="{{asset('/lib/flot-spline/js/jquery.flot.spline.min.js')}}"></script>
    <script src="{{asset('/lib/jquery-sparkline/jquery.sparkline.min.js')}}"></script>
    <script src="{{asset('/lib/echarts/echarts.min.js')}}"></script>
    <script src="{{asset('/lib/select2/js/select2.full.min.js')}}"></script>
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyAq8o5-8Y5pudbJMJtDFzb8aHiWJufa5fg"></script>
    <script src="{{asset('/lib/gmaps/gmaps.min.js')}}"></script>

    <script src="../js/bracket.js"></script>
    <script src="../js/map.shiftworker.js"></script>
    <script src="../js/ResizeSensor.js"></script>
    <script src="../js/dashboard.dark.js"></script>